- name: Build Web Version
        run: |
          # The -s USE_SDL=2 flag tells Emscripten to fetch SDL2 automatically
          emcc main.c -o index.html -s USE_SDL=2 -s WASM=1 --shell-file shell.html
